[package]
name = "canary-development/easyprofile"
version = "4.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

exclude = ["**"]
include = [
	"default.project.json",
	"src",
	"src/**",
	"LICENSE",
	"wally.toml",
	"README.md",
]

[dependencies]
Signal = "red-blox/signal@^2.0.0"
Future = "red-blox/future@^1.0.0"

[server-dependencies]
profileservice = "grilme99/profileservice@1.0.0"