[package]
name = "canary-development/easyprofile"
version = "4.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

exclude = ["**"]
include = [
	"default.project.json",
	"src",
	"src/**",
	"LICENSE",
	"wally.toml",
	"README.md",
]

[dependencies]
signal = "red-blox/signal@2.0.1"
future = "red-blox/future@1.0.1"

[server-dependencies]
profileservice = "grilme99/profileservice@1.0.0"